# Generated by Django 3.2.4 on 2021-12-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='chunk_id',
            new_name='chunk',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='texttochunk',
            old_name='text_id',
            new_name='text',
        ),
        migrations.AddField(
            model_name='texttochunk',
            name='chunk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='text_to_chunk', to='uploader.chunk'),
            preserve_default=False,
        ),
    ]
